//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char tile_block_bmp [] = {
0xFF, 0xE1, 0xE1, 0xE1, 0xE1, 0xE1, 0xE1, 0xFF,
};

const unsigned char tile_wall_bmp [] = {
0x7E, 0xF3, 0xED, 0xED, 0xED, 0xED, 0xF3, 0x7E, 
};
